export const DATA_SOURCE = Symbol("APP_DATA_SOURCE");
export const API_KEY_REPOSITORY = Symbol("API_KEY_REPOSITORY");
export const REPOSITORY_REPOSITORY = Symbol("REPOSITORY_REPOSITORY");
export const USER_REPOSITORY = Symbol("USER_REPOSITORY");
export const AUDIT_EVENT_REPOSITORY = Symbol("AUDIT_EVENT_REPOSITORY");
export const COMMIT_REPOSITORY = Symbol("COMMIT_REPOSITORY");
export const SYNC_JOB_REPOSITORY = Symbol("SYNC_JOB_REPOSITORY");
